spring:
  task:
    scheduling:
      #????????? ?? 1
      pool:
        size: 1
      #???????? ?? scheduling-
      thread-name-prefix: qgt_
      shutdown:
        #?????????????
        await-termination: false
        #??????????????????????
        await-termination-period: 10s