#应用环境
spring:
  profiles:
    active: dev
    group:
      "dev": cache
      "pro":
      "test":

#        <redis>
#  data:
#    redis:
#      host: localhost
#      port: 6379
#  cache:
#    redis:
##      use-key-prefix: false #是否使用前缀
#      time-to-live: 10s   #保存时间
#      cache-null-values: false  #是否存储空值
##      key-prefix: gt  #前缀
#    type: redis



#设置日志模板格式
#logging:
#  pattern:
#    console: "%d %clr(%5p) --- [%16t] %clr(%-40.40c){cyan} : %m %n"
#  file:
#    name: server.log
#  logback:
#    rollingpolicy:
#      max-file-size: 4KB
#      file-name-pattern: server.%d{yyyy-MM-dd}.%i.log

